const msg = {
    usernameR: '请输入账号',
    usernameS: '请输入正确的手机或者邮箱',
    passwordR: '请输入密码',
    repasswordR: '请输入确认密码',
    captchaR: '请输入验证码',
    captchaT: '请输入手机验证码',
    captchaS: '验证码错误',
    phoneR: '请输入手机号码',
    smsR: '请输入短信验证码',
    emailCodeR: '请输入邮件验证码',
    agreeR: '请阅读协议',
    emailR: '请输入邮箱',
    phoneS: '请输入正确的手机号',
    phoneCodeS: '手机验证码错误',
    emailCodeS: '邮箱验证码错误',
    emailS: '邮箱格式错误',
    passwordS: '6-20个数字、字母或符号区分大小写',
    repasswordS: '两次密码输入不一致',
    streetinfoR: '请输入详细地址',
    streetinfoS: '请填写真实收货人地址',
    streetinfoRule: '请填写真实收货人地址',
    postcodeR: '请输入邮政编码',
    postcodeS: '邮政编码错误',
    firstnameR: '请填写收货人姓名',
    firstnameRule: '请填写真实姓名',
    nicknameR: '请输入昵称',
    firstnameS: '最少2个字符，最多20个字符',
    addressR: '请选择地址',
    addressS: '请选择地区',
    requireRule: '请选择地区'
};

export default msg
